Handle error on connecting/disconnecting
cased/shell pull request #47
Opened 2023-02-15 00:13 UTC by rikasun

2023-02-15 00:43 UTC, rikasun commented on apps/shell/src/main.tsx
> +  // </StrictMode>,
@ashblue Do you know how to let the websocket connect network call only once in useEffect hook other than me disabling the strict mode in local? 

Currently two network calls creating two websocket sessions, first one will disconnect and clear all the workers who work for the second one, which is the one the frontend is connecting to.

2023-02-15 00:44 UTC, rikasun commented on shell/controllers/v2/api/prompt_sessions_controller.py
> +            self.set_status(status_code)
The request status was not picking up from the errors before.

2023-02-15 17:57 UTC, ashblue commented on apps/shell/src/main.tsx
> +  // </StrictMode>,
Oh no, we have to have `<StrictMode>` turned on. It opens up the app to all sorts of memory leaks and other potential issues we will only see in production builds. It surfaces a lot of issues in development mode you definitely want to fix.

Strict mode doubles all calls for good reason to deter the possibility of side effects. There are several ways you could limit the socket connections. Below are some of the most straightforward ways I can think of to handle them.

* Use a flag to determine a websocket connection is being made on the store and block all future connections until it's cleared. Easy but can get messy.
* Move the websocket connection logic into a service layer and subscribe to events. This is definitely my preferred way of handling websockets (service based). But I think it would require a good bit of refactoring with the current architecture

2023-02-15 18:04 UTC, ashblue requested changes
The user experience here looks amazing!!! Great job. 

Minor feedback. Just need to turn strict mode back on and fix the duplicate socket connections.

2023-02-15 18:04 UTC, ashblue commented on libs/redux/src/lib/stores/prompt/prompt.store.ts
> +          const { response } = error as AxiosError<{ status: string }>;
Hmmm, this pattern shows up a lot in different forms, could use a DRY pass. Also would be nice if we could quick convert errors more easily. Can you create a utility function to process and return an axios error like `errorToAxiosError(error)` in the utilities library?

2023-02-15 18:04 UTC, ashblue commented on libs/redux/src/lib/stores/prompt/prompt.store.ts
> +        ws.onClose((evt) => actions.dispose(evt));
I think you can pass a self executing function here I believe.

```suggestion
        ws.onClose(actions.dispose);
```

2023-02-15 18:04 UTC, ashblue commented on libs/remotes/src/lib/prompt/prompt-service.ts
> +        `Shell connection failed. Data missing. ${errorMessage} See logs for details`,
```suggestion
        `Shell connection failed. Data missing. ${errorMessage}. See logs for details`,
```

2023-02-16 01:02 UTC, rikasun commented on apps/shell/src/main.tsx
> +  // </StrictMode>,
https://github.com/cased/shell/pull/47/commits/db873fa91cebeafb6404750ee605036d2695a0b8 
In this commit:
- we have a local variable to only init terminal once, we can further move terminal to the store later
-  The unsubscription part had to go because it was hit before first websocket request was called so we have no other way to flag the request was made or not, but once we move terminal to store it should be ok.

2023-02-16 01:04 UTC, rikasun commented on libs/redux/src/lib/stores/prompt/prompt.store.ts
> +          const { response } = error as AxiosError<{ status: string }>;
let me create a new PR so review will be easier. it will touch a bunch of new files

2023-02-16 17:22 UTC, ashblue commented on libs/redux/src/lib/stores/prompt/prompt.store.ts
> +          const { response } = error as AxiosError<{ status: string }>;
Sounds good, happy to pair if you want on this (seems a bit tricky)

2023-02-16 23:33 UTC, ashblue approved these changes
Looks good. Minor feedback. Only thing worth addressing might be moving that websocket connection limiter flag into the store. Beyond that the code here is top notch.

2023-02-16 23:33 UTC, ashblue commented on apps/shell/src/app/modules/prompt/prompt.tsx
> +let terminalMounted = false;
Nice, this is the simplest way to fix the issue. The hoisted variable is a good way to globally determine a connection. But it won't protect against the store getting into a corrupted state where the websocket connections are broken. Also if we add more websocket connection logic in the store or delete this component the flag failsafe will be lost.

Is it possible to move this flag with its check into the prompt store easily? If not just file a ticket and we can move it at a later date. Safe for now, or at least until we try to start modifying the prompt websocket connection logic.

2023-02-16 23:33 UTC, ashblue commented on apps/shell/src/main.tsx
> +    <App />,
Looks like a comma snuck in here. This will give every page a comma at the end of it.

```suggestion
    <App />
```

2023-02-16 23:33 UTC, ashblue commented on libs/redux/src/lib/stores/prompt/prompt.store.ts
> +        console.error('Connection already in progress');
Perfect, we need to console log more prompt errors at the store level.

2023-02-17 01:24 UTC, rikasun commented on apps/shell/src/app/modules/prompt/prompt.tsx
> +let terminalMounted = false;
The component doesn't seem to be able to get the updated store state fast enough for the second useEffect call, feels similar to the useState state not updating.

2023-02-17 01:33 UTC, rikasun commented on apps/shell/src/main.tsx
> +    <App />,
oops😅

2023-02-17 18:20 UTC, merged