Move terminal to redux store
cased/shell pull request #80
Opened 2023-03-01 03:04 UTC by rikasun

2023-03-02 19:51 UTC, rikasun commented
@ashblue I did a bunch of hack to get the test pass because of https://linear.app/cased/issue/CAS-475/cant-init-another-terminal-unless-page-reload
Let me know if you have any better solutions! Thanks!

2023-03-02 23:06 UTC, ashblue requested changes
This looks great. The component is much cleaner and easier to read. I think we can remove a lot of the extra code I flagged with some spies on factory generator. Also I noticed some memory leaks caused by scoping on the window resize event that should be easy to clean up.

PS Happy to do a pair to tackle the tagged extra testing blocks. Removing them will get rid of the remaining hacks.

2023-03-02 23:06 UTC, ashblue commented on libs/redux/src/lib/stores/prompt/prompt.store.ts
> +      if (!term) return;
These lines here seem odd. Does a test need a default value in the store for terminal maybe?

2023-03-02 23:06 UTC, ashblue commented on apps/shell/src/app/modules/prompt/prompt.tsx
> +window.terminalMounted = false;
Should be a work around to remove this in the test suite. Probably just need to adjust the factory class generator.

2023-03-02 23:06 UTC, ashblue commented on apps/shell/src/app/modules/prompt/prompt.spec.tsx
> +  });
I think we can just spy on the factory for the terminal classes and avoid this.

2023-03-07 23:38 UTC, ashblue approved these changes
Rika and I paired for a significant refactor on the code to add a few abstraction layers. It removes a large number of if statements, centralizes xterm usage, and allows for custom terminal line writing commands.

2023-03-08 00:04 UTC, merged