Static snippets
cased/shell pull request #82
Opened 2023-03-02 02:27 UTC by rikasun

2023-03-06 18:53 UTC, ashblue requested changes
* Swap JS hovers in `list-item` for CSS classes
* Swap radix dialogue library for a simple modal pattern
  * Move modal logic into the app unless we're going to use that specific modal multiple times. Probably worth creating a re-usable modal at some point in the future. But probably too much to do right now. If we were to do a re-usable modal it should look something like this https://mui.com/material-ui/react-modal/

2023-03-06 18:53 UTC, ashblue commented on libs/ui/src/lib/snippets/list-item/list-item.tsx
> +      onBlur={() => {}}
Shouldn't need to override these events. Guessing leftover copilot code.

2023-03-06 18:53 UTC, ashblue commented on apps/shell/src/app/modules/prompt/snippets/snippets.tsx
> +      ['GitHub', 'Kubernetes', 'Uncategorized'].map((name) => (
Good data driven design here

2023-03-06 18:53 UTC, ashblue commented on apps/shell/src/app/modules/prompt/snippets/snippets.tsx
> +                  onClick={() => {}}
Why is the onclick blank?

2023-03-08 00:11 UTC, rikasun commented on libs/ui/src/lib/snippets/list-item/list-item.tsx
> +      onBlur={() => {}}
it was typescript but I don't need them anymore after using tailwind css only.

2023-03-08 02:53 UTC, rikasun commented on libs/ui/src/lib/snippets/list-item/list-item.tsx
> +    >
Good catch! updated in https://github.com/cased/shell/pull/82/commits/3ce8495ecc4253a150479d22bef5963164bfd8a6

2023-03-08 02:54 UTC, rikasun commented on libs/ui/src/lib/snippets/dialog/dialog.tsx
> +import * as Dialog from '@radix-ui/react-dialog';
Updated in https://github.com/cased/shell/pull/82/commits/9bbc3decbef278ef4d94bfa076400928509eb614. I also removed the library.

2023-03-08 02:55 UTC, rikasun commented on apps/shell/src/app/modules/prompt/snippets/snippets.scss
> +}
This is gone after we remove radix. The css `modal modal-open` seems to work!

2023-03-08 02:55 UTC, rikasun commented on apps/shell/src/app/modules/prompt/snippets/snippets.tsx
> +              <input
Added in https://github.com/cased/shell/pull/82/commits/b8d0d9956780cb23975d466f2b1bcd6399956e60

2023-03-08 02:57 UTC, rikasun commented on apps/shell/src/app/modules/prompt/snippets/snippets.tsx
> +                  onClick={() => {}}
I wasn't ready to put in local state or redux then but I added in https://github.com/cased/shell/pull/82/commits/e2e185bd3f02bede4250af3c9b7bf704eaabbc7d now

2023-03-08 17:43 UTC, ashblue approved these changes
Minor feedback and a handful of comments to hopefully spark some fun conversations on design architecture. Great job on this!!! :shipit:

2023-03-08 17:43 UTC, ashblue commented on apps/shell/src/app/modules/prompt/snippets/category.tsx
> +        className,
I think you can use the object syntax for readability here.

```suggestion
        className,
        {
          'font-bold': selectedCategory === name,
        },
```

2023-03-08 17:43 UTC, ashblue commented on package.json
> -    "@radix-ui/react-dialog": "^0.1.1",
Super duper thank you for removing this. Large dependencies lightly used like this are always a little scary for maintenance.

2023-03-08 17:43 UTC, ashblue commented on apps/shell/src/app/modules/prompt/snippets/list-item.tsx
> +      className="w-full border-t border-zinc-800 py-2 px-4 text-left first-of-type:border-0 hover:cursor-pointer hover:bg-blue-700 hover:text-white"
Thank you for moving all those class names into the component. I'm sure it wasn't easy converting all that old SCSS code.

2023-03-08 17:43 UTC, ashblue commented on apps/shell/src/app/modules/prompt/snippets/snippets.tsx
> +          />
There's actually a much easier way to structure labels (see below). Also try to think of the label name in two ways.

* Screen readers will hear this label name for anybody with a disability who is trying to find a specific input
* The name will help greatly with E2Es and testing. As the label can be used as a pseudo ID to find an input

That said, here are some proposed tweaks below that could help with usability on this. Not sure this is 100% correct, but worth considering.

```suggestion
          <label>
            {/* adding sr-only will hide the text safely, but still make it usable for tests and screen readers */}
            <span className="mb-1 mr-2 text-sm">Argument 1</span>
            <input
              type="text"
              className="border border-zinc-600 bg-transparent text-sm focus:bg-transparent focus:outline-none"
              value="input1"
              onChange={() => {}}
            />
          </label>
```

2023-03-08 17:43 UTC, ashblue commented on apps/shell/src/app/modules/prompt/snippets/snippets.tsx
> +export default function Snippets() {
Might be worth moving this to a separate file. File is getting a bit long (lots of HTML).

2023-03-08 17:43 UTC, ashblue commented on apps/shell/src/app/modules/prompt/snippets/snippets.tsx
> +              </label>
This syntax looks odd. Shouldn't this be a button type submit instead?

2023-03-08 17:43 UTC, ashblue commented on apps/shell/src/app/modules/prompt/snippets/snippets.tsx
> +                <input
```suggestion
              <label>
                <span className="sr-only">Search Snippets</span>
                <input
```

2023-03-08 17:43 UTC, ashblue commented on libs/ui/src/lib/modal/modal.tsx
> +export function Modal({ open, children }: IModal) {
Nice! We can definitely use this as a component to build on. We can add things like `<ModalHeader />`, `<ModalClose />`, `<Box />`, etc as we go. And we can leave the styling to Ben when he wants to globally tweak all the modals.

2023-03-08 17:43 UTC, ashblue commented on libs/ui/src/lib/modal/modal.tsx
> +      clsx('modal bg-black/50', { 'modal-open': open, 'modal-closed': !open }),
Looks like we're using the Daisy UI modal syntax here. What about just using Tailwind instead so we have more granular control? Something like this maybe?

```suggestion
      clsx('fixed top-0 left-0 w-full h-full bg-black/50', { 'modal-open': open, 'modal-closed': !open }),
```

2023-03-08 17:43 UTC, ashblue commented on libs/ui/src/lib/modal/modal.tsx
> +  return <div className={modalClass}>{children}</div>;
Might be worth adding a close click area here. That way clicking outside the content will close the window automatically.

```suggestion
  const [isOpen, setIsOpen] = useState(open);
  
  useEffect(() => {
    setIsOpen(open);
  }, [open]);

  return <div className={modalClass}>
    <div onClick={() => setIsOpen(false)} className="absolute top-0 left-0 w-full h-full" />
    {children}
  </div>;
```

Above suggestion should give you two way binding control. If that gives you any trouble with your current implementation it's okay to skip on this for now.

2023-03-08 19:29 UTC, rikasun commented on libs/ui/src/lib/modal/modal.tsx
> +      clsx('modal bg-black/50', { 'modal-open': open, 'modal-closed': !open }),
I was wondering which lib these `css` are from in the permission modal!😅 If we remove`modal`, the `modal-open` and `modal-close` doesn't seem to work so I put modal back for now.
Do we want to use the css in https://tailwind-elements.com/docs/standard/components/modal/?

2023-03-08 19:31 UTC, rikasun commented on libs/ui/src/lib/modal/modal.tsx
> +  return <div className={modalClass}>{children}</div>;
I was wondering how to do this. This works great! But we just need to coordinate the z-index we applied to different layers in the future, so far
xterm: z-10
close area: z-20
command pallet: z-50

2023-03-08 19:54 UTC, rikasun commented on apps/shell/src/app/modules/prompt/snippets/snippets.tsx
> +              </label>
Updated to button. Lots of signup/login form seem to use submit input.

2023-03-08 20:50 UTC, ashblue commented on libs/ui/src/lib/modal/modal.tsx
> +      clsx('modal bg-black/50', { 'modal-open': open, 'modal-closed': !open }),
I was wondering about that. All good, we can start with Daisy UI and transition off. We actually don't use the tailwind component library though. Sadly we don't have access to that CSS link.

2023-03-08 20:52 UTC, ashblue commented on libs/ui/src/lib/modal/modal.tsx
> +  return <div className={modalClass}>{children}</div>;
Yeah the parent class will probably need a Z index. We should probably figure out some sorta strategy to our z index layers 🤔 Maybe Ben has a good idea on how to best organize this as Tailwind's z index layers are pretty vague.

2023-03-08 20:53 UTC, ashblue commented on apps/shell/src/app/modules/prompt/snippets/snippets.tsx
> +              </label>
You're right that a lot of forms use that pattern. But it's the old way of approaching submit buttons (pre HTML5). Using a modern button is better for a lot of reasons 😄

2023-03-08 22:37 UTC, merged